name: Astro Node.js CI

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 1.5

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - uses: actions/checkout@v4
      - name: Setup environment
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci

      - name: Check formatting
        continue-on-error: true
        run: npm run fmt

      - name: Run linter
        run: npx astro check

      - name: Build
        run: npm run build

      - name: Test server run
        run: npm run preview &

      - name: Test server (cURL)
        run: curl http://localhost:4321

      - name: Test server (netcat)
        run: nc -zv localhost 4321

      - name: Prep deployment
        uses: actions/checkout@v4.2.2

      - name: Deploy
        run: |
          curl -X POST \
            -H "Authorization: bearerAuth ${{ secrets.COOLIFY_AUTH_TOKEN }}" \
            -H "Content-Type: application/json" \
            -D "bearerAuth=${{ secrets.COOLIFY_AUTH_TOKEN }}" \
            "${{ secrets.COOLIFY_URL }}"
